version: '3'
services:
  mongodb:
<<<<<<< HEAD
<<<<<<< HEAD
    image: mongo:latest
    container_name: mongodb-container
    image: mongo
=======
    build:
      context: .
      dockerfile: mongo\Dockerfile
>>>>>>> parent of ed9160c (.)
=======
    build:
      context: .
      dockerfile: mongo\Dockerfile
>>>>>>> parent of ed9160c (.)
    ports:
      - "27017:27017"
    networks:
      - app-network

  go-app:
    build:
      context: .
      dockerfile: go\Dockerfile
    depends_on:
      - mongodb

  front-app:
    build:
      context: .
      dockerfile: front\Dockerfile
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge