version: '3'

services:
  mongodb:
    build:
      context: .
      dockerfile: mongo\Dockerfile
    ports:
      - "27017:27017"
    networks:
      - app-network

  go-app:
    build:
      context: .
      dockerfile: go\Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - app-network

  front-app:
    build:
      context: .
      dockerfile: front\Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge