version: '3'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - volumen_tp:/data/db


  go-app:
    build:
      context: .
      dockerfile: go/Dockerfile
    container_name: go-app-container
    depends_on:
      - mongodb      
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./front/html:/app/front/html

  # Servicio del frontend (web-app)
  web-app:
    build:
      context: ./front   
      dockerfile: Dockerfile
    container_name: web-app-container
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - go-app        

networks:
  app-network:
    driver: bridge

volumes:
  volumen_tp:
