version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - volumen_tp:/data/db
    healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 5s
        retries: 5


  backend:
      build:
        context: .
        dockerfile: DockerfileBack
      ports:
        - "8080:8080"
      volumes:
        - /app/html  # Incluye las plantillas HTML
        - /app/css   # Incluye los archivos CSS
        - /app/js    # Incluye los archivos JS
      environment:
        - GIN_MODE=debug
      
      depends_on:
        mongodb:
          condition: service_healthy


      
  web-app:
    build:
      context: . 
      dockerfile: DockerfileFront
    container_name: web-app-container
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend        

networks:
  app-network:
    driver: bridge

volumes:
  volumen_tp:

