
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  go-app:
    build:
      context: ./go
      dockerfile: DockerfileBack
    container_name: go-app-container
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - app-network

  web-app:
    build:
      context: ./web
      dockerfile: DockerfileFront
    container_name: web-app-container
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - go-app

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
